# Generated by Django 2.2 on 2019-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='usage_period_summer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Период использования летом'),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='usage_period_winter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Период использования зимой'),
        ),
    ]
