# Generated by Django 2.2 on 2019-04-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0002_auto_20190404_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='services_summer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Летние возможности'),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='services_winter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Зимние возможности'),
        ),
    ]
