# Generated by Django 2.2 on 2019-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0003_auto_20190404_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='paid_comment',
            field=models.TextField(blank=True, verbose_name='Информация о оплате'),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='surface_type_summer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип летнего покрытия'),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='surface_type_winter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип зимнего покрытия'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Платное посещение'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='services_summer',
            field=models.TextField(blank=True, verbose_name='Летние сервисы'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='services_winter',
            field=models.TextField(blank=True, verbose_name='Зимние сервисы'),
        ),
    ]
