# Generated by Django 2.2 on 2019-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0004_auto_20190405_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='equipment_rental_commenst',
            field=models.TextField(blank=True, verbose_name='Информация о прокате'),
        ),
    ]
