# Generated by Django 2.2 on 2019-04-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0005_geoobject_equipment_rental_commenst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoobject',
            old_name='paid_comment',
            new_name='paid_comments',
        ),
    ]
