# Generated by Django 2.2 on 2019-04-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0006_auto_20190405_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='tech_service_comments',
            field=models.TextField(blank=True, verbose_name='Информация о сервисе'),
        ),
    ]
