# Generated by Django 2.2 on 2019-04-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0007_geoobject_tech_service_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoobject',
            old_name='equipment_rental_commenst',
            new_name='equipment_rental_comments',
        ),
    ]
