# Generated by Django 2.2 on 2019-04-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0008_auto_20190405_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='disability_friendly',
            field=models.CharField(max_length=50, verbose_name='Приспособлено для инвалидов'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес электронной почты для связи'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='paid',
            field=models.CharField(blank=True, max_length=50, verbose_name='Платное посещение'),
        ),
    ]
