# Generated by Django 2.2 on 2019-04-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0009_auto_20190405_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='paid_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о оплате'),
        ),
    ]
