# Generated by Django 2.2 on 2019-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0012_auto_20190405_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='disability_friendly',
            field=models.CharField(blank=True, max_length=50, verbose_name='Приспособлено для инвалидов'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='help_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='lighting',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Освещение'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='name_summer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Летнее название'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='name_winter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Зимнее название'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='paid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Платное посещение'),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='web_site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес сайта'),
        ),
    ]
