# Generated by Django 2.2 on 2019-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0014_auto_20190405_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='disability_friendly',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Приспособлено для инвалидов'),
        ),
    ]
