# Generated by Django 2.2 on 2019-04-06 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0015_auto_20190405_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 6, 30, 43, 630971, tzinfo=utc), verbose_name='Дата загрузки'),
        ),
    ]
