# Generated by Django 2.2 on 2019-04-06 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0016_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 10, 14, 34, 762717, tzinfo=utc), verbose_name='Дата загрузки'),
        ),
    ]
