# Generated by Django 2.2 on 2019-04-08 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0017_auto_20190406_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 16, 26, 17, 872064, tzinfo=utc), verbose_name='Дата загрузки'),
        ),
    ]
