# Generated by Django 2.2 on 2019-04-09 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0018_auto_20190408_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ya_preset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yandex settings'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ya_preset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yandex settings'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 3, 48, 44, 987980, tzinfo=utc), verbose_name='Дата загрузки'),
        ),
    ]
