# Generated by Django 2.2 on 2019-04-09 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0019_auto_20190409_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='geoobject',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='photo',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
    ]
