# Generated by Django 2.2 on 2019-04-12 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0020_auto_20190409_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='has_manual_cahanges',
            field=models.BooleanField(default=False, verbose_name='Признак наличия ручной правки'),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='photo',
            name='season',
            field=models.CharField(choices=[('S', 'Лето'), ('W', 'Зима')], default='W', max_length=20, verbose_name='Сезон'),
        ),
    ]
