# Generated by Django 2.2 on 2019-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0021_auto_20190412_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор в API'),
        ),
    ]
