# Generated by Django 2.2 on 2019-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0023_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Булевая платность'),
        ),
    ]
