# Generated by Django 2.2 on 2019-04-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuesapp', '0024_geoobject_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='has_light',
            field=models.BooleanField(default=False, verbose_name='Наличие освещения'),
        ),
    ]
